### ISSUE TITLE
How can i make state expand on CLick ?

### ISSUE THREAD

**Issue by UmairAhmed420** [TayfunCesur/CurvedBottomSheet#3]

**Comment by TayfunCesur** [comment]
Hello, sorry for the late reply.

You have access to get the`BottomSheetBehavior` from `CurvedBottomSheet`

You should get the instance of `CurvedBottomSheet` and get the `bottomSheetBehavior`. Then you can play with it,

```
val cur = CurvedBottomSheet((displayMetrics.widthPixels/6).toFloat(),view = bottom_sheet).init()
cur.bottomSheetBehavior.state = BottomSheetBehavior.STATE_EXPANDED
```
